events { 
    worker_connections 1024; 
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Mappiamo i tipi di file specifici della tua navicella 3D e delle texture
    types {
        text/plain                            obj mtl;
        image/png                             png;
        application/javascript                js;
        text/html                             html htm;
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }
}