http {
    # Include i tipi MIME standard del sistema (copre css, html, js, png, jpg, ecc.)
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Estendiamo i tipi MIME solo per quello che manca nello standard
    types {
        text/plain                            obj mtl;
        application/json                      gltf;
        application/octet-stream              glb;
    }

    server {
        # Ascolta sulla porta fissa 80, sincronizzata con il pannello di Railway
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            
            # Evita che il browser si tenga in cache i vecchi modelli 3D
            add_header Cache-Control "no-cache, must-revalidate";
        }
    }
}