# Configurazione dei tipi MIME aggiuntivi per i modelli 3D
types {
    text/plain                            obj mtl;
    application/json                      gltf;
    application/octet-stream              glb;
}

server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        
        # Evita la cache per i file di Blender durante i test
        add_header Cache-Control "no-cache, must-revalidate";
    }
}